# helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
# helm install my-opentelemetry-operator open-telemetry/opentelemetry-operator \

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-k8s

admissionWebhooks:
  certManager:
    enabled: true
  autoGenerateCert:
    enabled: false
